config/routes.rb
RiddlerAdmin::Engine.routes.draw do
  root to: "dashboard#index"

  resources :actions do
    put "sort", on: :collection
  end

  resources :elements do
    put "sort", on: :collection
  end

  resources :feature_flags do
    get "internal_preview", on: :member
  end

  resources :preview_contexts

  resources :publish_requests do
    post "approve", on: :member
    post "publish", on: :member
  end

  resources :steps do
    put "sort", on: :collection

    get "internal_preview", on: :member
    post "preview", on: :member
    get "preview", on: :member
    get "toggle", on: :member
  end

  resources :slugs
end

app/models/riddler_admin/action.rb
module RiddlerAdmin
  class Action < ::RiddlerAdmin::ApplicationRecord
    MODEL_KEY = "act".freeze
    CARDINALITY = :small

    belongs_to :actionable, polymorphic: true, validate: true

    acts_as_list scope: [:actionable_type, :actionable_id, :transition_type]

    validates :transition_type, presence: true, inclusion: { in: %w[ enter exit ] }

    # Alphanumeric and underscore only - no whitespace.
    # We might consider doing lowercase only for snake casing.
    validates :name, presence: true,
      format: {
        with: /\A[a-z][a-zA-Z0-9_]*\z/,
        message: "must be a valid variable name (no spaces, start with character)"
      }

    validates_uniqueness_of :name, scope: [:actionable_type, :actionable_id]

    validates :include_predicate, parseable_predicate: true

    before_validation :set_defaults

    def self.available_classes
      [
        Actions::Assignment,
        Actions::HTTPRequest
      ]
    end

    def self.default_class
      Actions::Assignment
    end

    def self.short_name
      name.demodulize
    end

    def short_name
      self.class.short_name
    end

    def object
      type.demodulize
    end

    def to_partial_path detail=nil
      [self.class.name.underscore, detail].compact.join "/"
    end

    def definition_hash options=nil
      options ||= {}
      hash = serializable_hash options.merge(serializable_hash_options)
      hash["type"] = object
      if hash["include_predicate"].blank?
        hash.delete "include_predicate"
      else
        hash["include_predicate_instructions"] = ::Predicator.compile hash["include_predicate"]
      end
      hash
    end

    def serializable_hash_options
      {
        except: excluded_attrs
      }
    end

    def excluded_attrs
      [:created_at, :updated_at, :actionable_type, :actionable_id, :position, :transition_type, :options]
    end

    private

    def set_defaults
      self.name = short_name.underscore if name.blank?
    end
  end
end

app/models/riddler_admin/actions/assignment.rb
module RiddlerAdmin
  module Actions
    class Assignment < ::RiddlerAdmin::Action
      def self.model_name
        ::RiddlerAdmin::Action.model_name
      end

      def definition_hash opts=nil
        hash = super
        hash["variable"] = options["variable"]
        hash["value"] = options["value"]
        hash
      end
    end
  end
end

app/models/riddler_admin/actions/http_request.rb
module RiddlerAdmin
  module Actions
    class HTTPRequest < ::RiddlerAdmin::Action
      def self.model_name
        ::RiddlerAdmin::Action.model_name
      end

      def definition_hash opts=nil
        hash = super
        hash["request_method"] = options["request_method"]
        hash["url"] = options["url"]
        hash["body"] = options["body"]
        hash
      end
    end
  end
end

app/models/riddler_admin/application_record.rb
require "ulid"

module RiddlerAdmin
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    after_initialize :generate_id

    private

    def random_length
      return 16 unless self.class.const_defined? :CARDINALITY
      size = self.class.const_get :CARDINALITY

      case size
        when :small then 4
        when :medium then 8
        when :large then 12
        else 16
      end
    end

    def generate_id
      return if id.present?
      model_key = self.class.const_get :MODEL_KEY
      ulid = ULID.generate
      id_string = ulid[0...(10+random_length)]
      self.id = [model_key, id_string].join "_"
    end
  end
end

app/models/riddler_admin/content_definition.rb
require "riddler/protobuf/content_version_pb"
require "riddler/protobuf/content_management_services_pb"

module RiddlerAdmin
  class ContentDefinition < ::RiddlerAdmin::ApplicationRecord
    MODEL_KEY = "cdef".freeze
    ID_LENGTH = 5 # 916_132_832 per second

    DEFINITION_SCHEMA_VERSION = 1

    # The Step or Element being defined
    belongs_to :content, polymorphic: true

    # The PublishRequest that created this
    belongs_to :publish_request

    validates :definition, presence: true

    validates_uniqueness_of :version, scope: [:content_type, :content_id]

    before_validation :add_fields

    def description
      publish_request.title
    end

    def title
      "#{content.title} v#{version} - #{description}"
    end

    def to_proto
      ::Riddler::Protobuf::ContentVersion.new \
        id: id,
        created_at: created_at_proto,
        content_type: content.content_type,
        content_id: content.id,
        title: content.title,
        description: description,
        version: version,
        definition_schema_version: DEFINITION_SCHEMA_VERSION,
        definition_string: definition.to_json
    end

    def publish_to_remote
      content_management_grpc.create_content_version create_request_proto
    end

    private

    def created_at_proto
      ::Google::Protobuf::Timestamp.new seconds: created_at.to_i,
        nanos: created_at.nsec
    end

    def create_request_proto
      ::Riddler::Protobuf::CreateContentVersionRequest.new \
        content_version: self.to_proto
    end

    def content_management_grpc
      ::Riddler::Protobuf::ContentManagement::Stub.new \
        ::RiddlerAdmin.configuration.riddler_grpc_address,
        :this_channel_is_insecure
    end

    def add_fields
      return if self.persisted? || content.blank?

      self.definition_schema_version = DEFINITION_SCHEMA_VERSION
      self.version = next_version
      self.definition = generate_definition self.version
    end

    def next_version
      previous_max = self.class.where(content: content).maximum(:version) || 0
      previous_max + 1
    end

    def generate_definition version
      generated_definition = content.definition_hash.merge({
        "definition_id" => id,
        "definition_schema_version" => DEFINITION_SCHEMA_VERSION,
        "version" => version
      })
    end
  end
end

app/models/riddler_admin/content_version.rb
require "riddler/protobuf/content_version_pb"
require "riddler/protobuf/content_management_services_pb"

module RiddlerAdmin
  class ContentVersion < ::RiddlerAdmin::ApplicationRecord
    MODEL_KEY = "cver".freeze
    CARDINALITY = :small

    DEFINITION_SCHEMA_VERSION = 1

    # The Step or Element being defined
    belongs_to :content, polymorphic: true

    # The PublishRequest that created this
    belongs_to :publish_request

    validates :definition, presence: true

    validates_uniqueness_of :version, scope: [:content_type, :content_id]

    before_validation :add_fields

    def description
      publish_request.title
    end

    def title
      "#{content.title} v#{version} - #{description}"
    end

    def to_proto
      ::Riddler::Protobuf::ContentVersion.new \
        id: id,
        created_at: created_at_proto,
        content_type: content.content_type,
        content_id: content.id,
        title: content.title,
        description: description,
        version: version,
        definition_schema_version: DEFINITION_SCHEMA_VERSION,
        definition_string: definition.to_json
    end

    def publish_to_remote
      content_management_grpc.create_content_version create_request_proto
    end

    private

    def created_at_proto
      ::Google::Protobuf::Timestamp.new seconds: created_at.to_i,
        nanos: created_at.nsec
    end

    def create_request_proto
      ::Riddler::Protobuf::CreateContentVersionRequest.new \
        content_version: self.to_proto
    end

    def content_management_grpc
      ::Riddler::Protobuf::ContentManagement::Stub.new \
        ::RiddlerAdmin.configuration.riddler_grpc_address,
        :this_channel_is_insecure
    end

    def add_fields
      return if self.persisted? || content.blank?

      self.definition_schema_version = DEFINITION_SCHEMA_VERSION
      self.version = next_version
      self.definition = generate_definition self.version
    end

    def next_version
      previous_max = self.class.where(content: content).maximum(:version) || 0
      previous_max + 1
    end

    def generate_definition version
      generated_definition = content.definition_hash.merge({
        "definition_id" => id,
        "definition_schema_version" => DEFINITION_SCHEMA_VERSION,
        "version" => version
      })
    end
  end
end

app/models/riddler_admin/definition.rb
require "riddler/protobuf/definition_pb"

module RiddlerAdmin
  class Definition < ::RiddlerAdmin::ApplicationRecord
    MODEL_KEY = "cdef".freeze
    ID_LENGTH = 5 # 916_132_832 per second

    DEFINITION_SCHEMA_VERSION = 1

    # The Step or Element being defined
    belongs_to :content, polymorphic: true

    # The PublishRequest that created this
    belongs_to :publish_request

    validates :definition, presence: true

    validates_uniqueness_of :version, scope: [:content_type, :content_id]

    before_validation :add_fields

    def title
      "#{content.title} v#{version}"
    end

    def to_proto
      ::Riddler::Protobuf::Definition.new \
        schema_version: DEFINITION_SCHEMA_VERSION,
        id: id,
        created_at: created_at_proto,
        content_type: content.content_type,
        content_id: content.id,
        version: version,
        definition_json: definition.to_json
    end

    private

    def created_at_proto
      ::Google::Protobuf::Timestamp.new seconds: created_at.to_i,
        nanos: created_at.nsec
    end

    def add_fields
      return if self.persisted? || content.blank?

      self.schema_version = DEFINITION_SCHEMA_VERSION
      self.version = next_version
      self.definition = generate_definition self.version
    end

    def next_version
      previous_max = self.class.where(content: content).maximum(:version) || 0
      previous_max + 1
    end

    def generate_definition version
      generated_definition = content.definition_hash.merge({
        "definition_id" => id,
        "definition_schema_version" => DEFINITION_SCHEMA_VERSION,
        "version" => version
      })
    end
  end
end

app/models/riddler_admin/element.rb
module RiddlerAdmin
  class Element < ::RiddlerAdmin::ApplicationRecord
    MODEL_KEY = "el".freeze
    CARDINALITY = :medium

    after_initialize :set_defaults

    belongs_to :container, polymorphic: true, validate: true

    acts_as_list scope: [:container_type, :container_id]

    validates_presence_of :name

    # Alphanumeric and underscore only - no whitespace.
    # We might consider doing lowercase only for snake casing.
    validates_format_of :name, with: /\A[a-z][a-zA-Z0-9_]*\z/, message: "cannot start with a capital letter or a number."
    validates_uniqueness_of :name, scope: [:container_type, :container_id], unless: :is_variant?

    validates :include_predicate, parseable_predicate: true

    def self.available_classes
      [
        Elements::Heading,
        Elements::Image,
        Elements::Link,
        Elements::Text,
        Elements::Variant
      ]
    end

    def self.default_class
      Elements::Text
    end

    def self.short_name
      name.demodulize
    end

    def to_partial_path detail=nil
      [self.class.name.underscore, detail].compact.join "/"
    end

    def short_name
      self.class.short_name
    end

    # Used in serialization
    def object
      type.demodulize
    end

    def content_type
      "Element"
    end

    def content_id
      id
    end

    def definition_hash options=nil
      options ||= {}
      hash = serializable_hash options.merge(serializable_hash_options)
      hash["type"] = object
      if hash["include_predicate"].blank?
        hash.delete "include_predicate"
      else
        hash["include_predicate_instructions"] = ::Predicator.compile hash["include_predicate"]
      end
      hash
    end

    def serializable_hash_options
      {
        methods: [:content_type],
        except: excluded_attrs
      }
    end

    def excluded_attrs
      [:created_at, :updated_at, :container_type, :container_id, :position, :url, :text]
    end

    def step
      if container.kind_of? ::RiddlerAdmin::Step
        container
      else
        container.step
      end
    end

    private

    def is_variant?
      container.kind_of? ::RiddlerAdmin::Elements::Variant
    end

    def set_defaults
      self.name = short_name.underscore if name.blank?
    end
  end
end

app/models/riddler_admin/elements/button.rb
module RiddlerAdmin
  module Elements
    class Button < Element
      validates_presence_of :text

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["text"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/copy.rb
module RiddlerAdmin
  module Elements
    class Copy < Element
      validates_presence_of :text

      def self.model_name
        Element.model_name
      end
    end
  end
end

app/models/riddler_admin/elements/external_link.rb
module RiddlerAdmin
  module Elements
    class ExternalLink < Element
      validates_presence_of :url

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["href"] = url
        hash["text"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/heading.rb
module RiddlerAdmin
  module Elements
    class Heading < Element
      validates_presence_of :text

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["text"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/image.rb
module RiddlerAdmin
  module Elements
    class Image < Element
      validates_presence_of :url

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["src"] = url
        hash["alt"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/link.rb
module RiddlerAdmin
  module Elements
    class Link < Element
      validates_presence_of :url

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["href"] = url
        hash["text"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/question.rb
module RiddlerAdmin
  module Elements
    class Question < Element
      def self.model_name
        Element.model_name
      end
    end
  end
end

app/models/riddler_admin/elements/text.rb
module RiddlerAdmin
  module Elements
    class Text < Element
      validates_presence_of :text

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["text"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/text_question.rb
module RiddlerAdmin
  module Elements
    class TextQuestion < Elements::Question
      validates_presence_of :text

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["text"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/variant.rb
module RiddlerAdmin
  module Elements
    class Variant < Element
      has_many :elements, -> { order position: :asc },
        dependent: :destroy,
        as: :container

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["elements"] = elements.map { |e| e.definition_hash }
        hash
      end
    end
  end
end

app/views/riddler_admin/steps/_actions.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3">
      <h4>Add an action</h4>

      <ul class="nav flex-column">
      <% RiddlerAdmin::Action.available_classes.each do |klass| %>
        <%= link_to "#{klass.short_name}", new_action_path(type: klass.name, step_id: @step.id), remote: true, class: 'nav-link' %>
      <% end %>
      </ul>
    </div>
    <div class="col-md-9">
      <div id="new-action">
      </div>

      <%= render partial: "riddler_admin/action_container", locals: { actionable: @step } %>

    </div>
  </div>
</div>

app/views/riddler_admin/steps/_definition.html.erb
<div class="row">
  <div class="col-sm">
    <h4>Step Definition</h4>
  </div>
</div>

<div class="row">
  <div class="col-sm">
    <pre><%= definition.definition_hash.to_yaml %></pre>
  </div>
</div>

app/views/riddler_admin/steps/_form.html.erb
<%= form_with model: step, local: true do |form| %>
  <div class="row">
    <% if step.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(step.errors.count, "error") %> prohibited this step from being saved:</h2>

        <ul>
        <% step.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  </div>

  <div class="form-group">
    <div class="form-row">
      <div class="col">
        <%= form.label :title %>
        <%= form.text_field :title, class:"form-control" %>
      </div>
      <div class="col">
        <%= form.label :name %>
        <%= form.text_field :name, class:"form-control" %>
        <small class="form-text text-muted">This will be created based on the title if not provided</small>
      </div>
    </div>
    <% unless @step.persisted? %>
    <div class="form-row">
      <div class="col">
        <%= form.label :type %>
        <%= form.select :type, options_for_select(::RiddlerAdmin::Step.available_classes.map{|klass| [klass.short_name, klass.name]}, step.type), {}, class:"form-control" %>
      </div>
    </div>
    <% end %>
    <div class="form-row">
      <div class="col">
        <%= form.label :include_predicate %>
        <%= form.text_field :include_predicate, class: "form-control", placeholder: "e.g. params.user_id is present" %>
        <small class="form-text text-muted">Use data from the context that evaluates to <code>true</code> or <code>false</code></small>
      </div>
    </div>
    <div class="form-row">
      <div class="actions">
        <%= form.submit "Save step", class: "btn btn-primary" %>
        <%= link_to "Cancel", steps_path, class: "btn btn-light" %>
      </div>
    </div>
  </div>
<% end %>

app/views/riddler_admin/steps/_new_sub_step.html.erb
<%= form_with model: step do |form| %>
  <% if step.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(step.errors.count, "error") %> prohibited this step from being saved:</h2>

      <ul>
      <% step.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card" style="margin-bottom: 32px;">
    <div class="card-body">

      <div class="card-title">
        <h5>New <%= step.short_name %> Step</h5>
      </div>

      <%= form.hidden_field :type %>
      <%= form.hidden_field :stepable_type %>
      <%= form.hidden_field :stepable_id %>

      <div class="form-group">
        <div class="form-row">
          <div class="col">
            <%= form.label :title %>
            <%= form.text_field :title, class:"form-control" %>
          </div>
          <div class="col">
            <%= form.label :name %>
            <%= form.text_field :name, class:"form-control" %>
            <small class="form-text text-muted">This will be created based on the title if not provided</small>
          </div>
        </div>

        <div class="form-row">
          <div class="col">
            <%= form.label :include_predicate %>
            <%= form.text_field :include_predicate, class: "form-control", placeholder: "e.g. params.user_id is present" %>
            <small class="form-text text-muted">Use data from the context that evaluates to <code>true</code> or <code>false</code></small>
          </div>
        </div>


        <div class="form-row">
          <div class="actions">
            <%= form.submit "Add step", class: "btn btn-primary" %>
          </div>
        </div>
      </div>

    </div>
  </div>
<% end %>

app/views/riddler_admin/steps/_preview.html.erb
<div class="row">
  <div class="col-sm-3">
    <h4>Preview Contexts</h4>
    <div class="list-group" id="preview-sections-tab" role="tablist">
      <% @preview_contexts.each do |ctx| %>
        <a class="list-group-item list-group-item-action step-context-preview" id="list-preview-<%= ctx.id %>" data-step-id="<%= @step.id %>" data-pctx-id="<%= ctx.id %>" data-toggle="list" href="#preview-context-<%= ctx.id %>" role="tab" aria-controls="preview-context-<%= ctx.id %>"><%= ctx.title %></a>
      <% end %>
    </div>
  </div>
  <div class="col-sm-9">
    <div class="tab-content" id="nav-tabContent">
      <% @preview_contexts.each do |ctx| %>
        <div class="tab-pane fade" id="preview-context-<%= ctx.id %>" role="tabpanel" aria-labelledby="list-preview-context-<%= ctx.id %>">
          <ul class="nav nav-pills" id="<%= ctx.id %>-type" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" id="<%= ctx.id %>-visual-tab" data-toggle="tab" href="#<%= ctx.id %>-visual" role="tab" aria-controls="<%= ctx.id %>-visual" aria-selected="true">Visual</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="<%= ctx.id %>-json-tab" data-toggle="tab" href="#<%= ctx.id %>-json" role="tab" aria-controls="<%= ctx.id %>-json" aria-selected="false">JSON</a>
            </li>
          </ul>
          <div class="tab-content" id="<%= ctx.id %>-typeContent">
            <div class="tab-pane fade show active" id="<%= ctx.id %>-visual" role="tabpanel" aria-labelledby="<%= ctx.id %>-visual-tab">
            </div>
            <div class="tab-pane fade" id="<%= ctx.id %>-json" role="tabpanel" aria-labelledby="<%= ctx.id %>-json-tab">
              <pre></pre>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/riddler_admin/steps/_visual_preview.html.erb
<form>
<ul class="list-group">
  <% if data["elements"].blank? %>
    <li class="list-group-item">
      <%= data["message"] %>
    </li>
  <% else %>
    <% data["elements"].each do |element| %>
      <li class="list-group-item">
        <% case element["type"] %>
        <% when "Button" %>
          <button id="<%= element["id"] %>" class="btn btn-primary"><%= element["text"] %></button>
        <% when "Link" %>
          <a href="<%= element["href"] %>" target="_blank"><%= element["text"] %></a>
        <% when "Heading" %>
          <h5><%= element["text"] %></h5>
        <% when "Image" %>
          <img src="<%= element["src"] %>" alt="<%= element["alt"] %>" />
        <% when "Text" %>
          <%= element["text"] %>
        <% when "TextQuestion" %>
          <label for="<%= element["id"] %>"><%= element["text"] %></label><br/>
          <input id="<%= element["id"] %>" type="text" class="form-control" />
        <% else %>
          Unknown Element type "<%= element["type"] %>"
        <% end %>
      </li>
    <% end %>
  <% end %>
</ul>
</form>

app/views/riddler_admin/steps/edit.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm">
        <h1>Editing Step</h1>
      </div>
    </div>

    <div class="row">
      <div class="col-sm">
        <%= render 'form', step: @step %>

        <%= link_to 'Back', @step %>
      </div>
    </div>
  </div>
</div>

app/views/riddler_admin/steps/index.html.erb
<div class="row">
  <% if notice %>
  <div class="col-sm">
    <span id="notice"><%= notice %></span>
  </div>
  <% end %>
</div>

<div class="row">
  <div class="col-sm-6">
    <h1>Steps</h1>
  </div>
  <div class="col-sm-6">
    <%= link_to 'New step', new_step_path, class: 'btn btn-primary float-right'%>
  </div>
</div>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Id</th>
      <th>Type</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @steps.each do |step| %>
      <tr>
        <td><%= link_to step.title, step %></td>
        <td><%= step.id %></td>
        <td><%= step.type.demodulize %></td>

        <td>
            <%= link_to 'Delete', step, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-light' %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/riddler_admin/steps/new.html.erb
<div class="card">
  <div class="card-body">
    <div class="row">
      <div class="col-sm">
        <h1>New Step</h1>
      </div>
    </div>
    <%= render "form", step: @step %>
  </div>
</div>

app/views/riddler_admin/steps/new.js.erb
$("#new-step")
  .html("<%= j render partial: "new_sub_step", locals: { step: @step } %>")
  .show()

app/views/riddler_admin/steps/preview.js.erb
$("#step-preview-content")
  .html("<%= j JSON.pretty_generate @use_case.process %>")

app/views/riddler_admin/steps/show.html.erb
<div class="row">
  <div class="col-sm">
    <% if notice %>
    <div class="alert alert-success">
      <span id="notice"><%= notice %></span>
    </div>
    <% end %>
  </div>
</div>

<div class="row" style="margin-bottom: 32px;">
  <div class="col-sm-6">
    <h1><%= @step.title %></h1>
  </div>
  <div class="col-sm-6">
    <%= link_to 'Edit Step', edit_step_path(@step), class: 'btn btn-light float-right' %>
    <% if ::RiddlerAdmin.configuration.remote_riddler? %>
      <%= link_to "Publish", new_publish_request_path(step_id: @step.id), class: "btn btn-light float-right"%>
    <% end %>
  </div>
</div>

<%= render partial: @step.to_partial_path("show") %>

app/views/riddler_admin/steps/show.js.erb
$("#new-step").fadeOut().html("").show();

$("#<%= @step.stepable.id %>-steps")
  .html("<%= j render partial: "riddler_admin/step", collection: @step.stepable.steps %>")