config/routes.rb
RiddlerAdmin::Engine.routes.draw do
  root to: "dashboard#index"

  resources :actions do
    put "sort", on: :collection
  end

  resources :elements do
    put "sort", on: :collection
  end

  resources :feature_flags do
    get "internal_preview", on: :member
  end

  resources :preview_contexts

  resources :publish_requests do
    post "approve", on: :member
    post "publish", on: :member
  end

  resources :steps do
    put "sort", on: :collection

    get "internal_preview", on: :member
    post "preview", on: :member
    get "preview", on: :member
    get "toggle", on: :member
  end

  resources :slugs
end

app/models/riddler_admin/action.rb
module RiddlerAdmin
  class Action < ::RiddlerAdmin::ApplicationRecord
    MODEL_KEY = "act".freeze
    CARDINALITY = :small

    belongs_to :actionable, polymorphic: true, validate: true

    acts_as_list scope: [:actionable_type, :actionable_id, :transition_type]

    validates :transition_type, presence: true, inclusion: { in: %w[ enter exit ] }

    # Alphanumeric and underscore only - no whitespace.
    # We might consider doing lowercase only for snake casing.
    validates :name, presence: true,
      format: {
        with: /\A[a-z][a-zA-Z0-9_]*\z/,
        message: "must be a valid variable name (no spaces, start with character)"
      }

    validates_uniqueness_of :name, scope: [:actionable_type, :actionable_id]

    validates :include_predicate, parseable_predicate: true

    before_validation :set_defaults

    def self.available_classes
      [
        Actions::Assignment,
        Actions::HTTPRequest
      ]
    end

    def self.default_class
      Actions::Assignment
    end

    def self.short_name
      name.demodulize
    end

    def short_name
      self.class.short_name
    end

    def object
      type.demodulize
    end

    def to_partial_path detail=nil
      [self.class.name.underscore, detail].compact.join "/"
    end

    def definition_hash options=nil
      options ||= {}
      hash = serializable_hash options.merge(serializable_hash_options)
      hash["type"] = object
      if hash["include_predicate"].blank?
        hash.delete "include_predicate"
      else
        hash["include_predicate_instructions"] = ::Predicator.compile hash["include_predicate"]
      end
      hash
    end

    def serializable_hash_options
      {
        except: excluded_attrs
      }
    end

    def excluded_attrs
      [:created_at, :updated_at, :actionable_type, :actionable_id, :position, :transition_type, :options]
    end

    private

    def set_defaults
      self.name = short_name.underscore if name.blank?
    end
  end
end

app/models/riddler_admin/actions/assignment.rb
module RiddlerAdmin
  module Actions
    class Assignment < ::RiddlerAdmin::Action
      def self.model_name
        ::RiddlerAdmin::Action.model_name
      end

      def definition_hash opts=nil
        hash = super
        hash["variable"] = options["variable"]
        hash["value"] = options["value"]
        hash
      end
    end
  end
end

app/models/riddler_admin/actions/http_request.rb
module RiddlerAdmin
  module Actions
    class HTTPRequest < ::RiddlerAdmin::Action
      def self.model_name
        ::RiddlerAdmin::Action.model_name
      end

      def definition_hash opts=nil
        hash = super
        hash["request_method"] = options["request_method"]
        hash["url"] = options["url"]
        hash["body"] = options["body"]
        hash
      end
    end
  end
end

app/models/riddler_admin/application_record.rb
require "ulid"

module RiddlerAdmin
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true

    after_initialize :generate_id

    private

    def random_length
      return 16 unless self.class.const_defined? :CARDINALITY
      size = self.class.const_get :CARDINALITY

      case size
        when :small then 4
        when :medium then 8
        when :large then 12
        else 16
      end
    end

    def generate_id
      return if id.present?
      model_key = self.class.const_get :MODEL_KEY
      ulid = ULID.generate
      id_string = ulid[0...(10+random_length)]
      self.id = [model_key, id_string].join "_"
    end
  end
end

app/models/riddler_admin/content_definition.rb
require "riddler/protobuf/content_version_pb"
require "riddler/protobuf/content_management_services_pb"

module RiddlerAdmin
  class ContentDefinition < ::RiddlerAdmin::ApplicationRecord
    MODEL_KEY = "cdef".freeze
    ID_LENGTH = 5 # 916_132_832 per second

    DEFINITION_SCHEMA_VERSION = 1

    # The Step or Element being defined
    belongs_to :content, polymorphic: true

    # The PublishRequest that created this
    belongs_to :publish_request

    validates :definition, presence: true

    validates_uniqueness_of :version, scope: [:content_type, :content_id]

    before_validation :add_fields

    def description
      publish_request.title
    end

    def title
      "#{content.title} v#{version} - #{description}"
    end

    def to_proto
      ::Riddler::Protobuf::ContentVersion.new \
        id: id,
        created_at: created_at_proto,
        content_type: content.content_type,
        content_id: content.id,
        title: content.title,
        description: description,
        version: version,
        definition_schema_version: DEFINITION_SCHEMA_VERSION,
        definition_string: definition.to_json
    end

    def publish_to_remote
      content_management_grpc.create_content_version create_request_proto
    end

    private

    def created_at_proto
      ::Google::Protobuf::Timestamp.new seconds: created_at.to_i,
        nanos: created_at.nsec
    end

    def create_request_proto
      ::Riddler::Protobuf::CreateContentVersionRequest.new \
        content_version: self.to_proto
    end

    def content_management_grpc
      ::Riddler::Protobuf::ContentManagement::Stub.new \
        ::RiddlerAdmin.configuration.riddler_grpc_address,
        :this_channel_is_insecure
    end

    def add_fields
      return if self.persisted? || content.blank?

      self.definition_schema_version = DEFINITION_SCHEMA_VERSION
      self.version = next_version
      self.definition = generate_definition self.version
    end

    def next_version
      previous_max = self.class.where(content: content).maximum(:version) || 0
      previous_max + 1
    end

    def generate_definition version
      generated_definition = content.definition_hash.merge({
        "definition_id" => id,
        "definition_schema_version" => DEFINITION_SCHEMA_VERSION,
        "version" => version
      })
    end
  end
end

app/models/riddler_admin/content_version.rb
require "riddler/protobuf/content_version_pb"
require "riddler/protobuf/content_management_services_pb"

module RiddlerAdmin
  class ContentVersion < ::RiddlerAdmin::ApplicationRecord
    MODEL_KEY = "cver".freeze
    CARDINALITY = :small

    DEFINITION_SCHEMA_VERSION = 1

    # The Step or Element being defined
    belongs_to :content, polymorphic: true

    # The PublishRequest that created this
    belongs_to :publish_request

    validates :definition, presence: true

    validates_uniqueness_of :version, scope: [:content_type, :content_id]

    before_validation :add_fields

    def description
      publish_request.title
    end

    def title
      "#{content.title} v#{version} - #{description}"
    end

    def to_proto
      ::Riddler::Protobuf::ContentVersion.new \
        id: id,
        created_at: created_at_proto,
        content_type: content.content_type,
        content_id: content.id,
        title: content.title,
        description: description,
        version: version,
        definition_schema_version: DEFINITION_SCHEMA_VERSION,
        definition_string: definition.to_json
    end

    def publish_to_remote
      content_management_grpc.create_content_version create_request_proto
    end

    private

    def created_at_proto
      ::Google::Protobuf::Timestamp.new seconds: created_at.to_i,
        nanos: created_at.nsec
    end

    def create_request_proto
      ::Riddler::Protobuf::CreateContentVersionRequest.new \
        content_version: self.to_proto
    end

    def content_management_grpc
      ::Riddler::Protobuf::ContentManagement::Stub.new \
        ::RiddlerAdmin.configuration.riddler_grpc_address,
        :this_channel_is_insecure
    end

    def add_fields
      return if self.persisted? || content.blank?

      self.definition_schema_version = DEFINITION_SCHEMA_VERSION
      self.version = next_version
      self.definition = generate_definition self.version
    end

    def next_version
      previous_max = self.class.where(content: content).maximum(:version) || 0
      previous_max + 1
    end

    def generate_definition version
      generated_definition = content.definition_hash.merge({
        "definition_id" => id,
        "definition_schema_version" => DEFINITION_SCHEMA_VERSION,
        "version" => version
      })
    end
  end
end

app/models/riddler_admin/definition.rb
require "riddler/protobuf/definition_pb"

module RiddlerAdmin
  class Definition < ::RiddlerAdmin::ApplicationRecord
    MODEL_KEY = "cdef".freeze
    ID_LENGTH = 5 # 916_132_832 per second

    DEFINITION_SCHEMA_VERSION = 1

    # The Step or Element being defined
    belongs_to :content, polymorphic: true

    # The PublishRequest that created this
    belongs_to :publish_request

    validates :definition, presence: true

    validates_uniqueness_of :version, scope: [:content_type, :content_id]

    before_validation :add_fields

    def title
      "#{content.title} v#{version}"
    end

    def to_proto
      ::Riddler::Protobuf::Definition.new \
        schema_version: DEFINITION_SCHEMA_VERSION,
        id: id,
        created_at: created_at_proto,
        content_type: content.content_type,
        content_id: content.id,
        version: version,
        definition_json: definition.to_json
    end

    private

    def created_at_proto
      ::Google::Protobuf::Timestamp.new seconds: created_at.to_i,
        nanos: created_at.nsec
    end

    def add_fields
      return if self.persisted? || content.blank?

      self.schema_version = DEFINITION_SCHEMA_VERSION
      self.version = next_version
      self.definition = generate_definition self.version
    end

    def next_version
      previous_max = self.class.where(content: content).maximum(:version) || 0
      previous_max + 1
    end

    def generate_definition version
      generated_definition = content.definition_hash.merge({
        "definition_id" => id,
        "definition_schema_version" => DEFINITION_SCHEMA_VERSION,
        "version" => version
      })
    end
  end
end

app/models/riddler_admin/element.rb
module RiddlerAdmin
  class Element < ::RiddlerAdmin::ApplicationRecord
    MODEL_KEY = "el".freeze
    CARDINALITY = :medium

    after_initialize :set_defaults

    belongs_to :container, polymorphic: true, validate: true

    acts_as_list scope: [:container_type, :container_id]

    validates_presence_of :name

    # Alphanumeric and underscore only - no whitespace.
    # We might consider doing lowercase only for snake casing.
    validates_format_of :name, with: /\A[a-z][a-zA-Z0-9_]*\z/, message: "cannot start with a capital letter or a number."
    validates_uniqueness_of :name, scope: [:container_type, :container_id], unless: :is_variant?

    validates :include_predicate, parseable_predicate: true

    def self.available_classes
      [
        Elements::Heading,
        Elements::Image,
        Elements::Link,
        Elements::Text,
        Elements::Variant
      ]
    end

    def self.default_class
      Elements::Text
    end

    def self.short_name
      name.demodulize
    end

    def to_partial_path detail=nil
      [self.class.name.underscore, detail].compact.join "/"
    end

    def short_name
      self.class.short_name
    end

    # Used in serialization
    def object
      type.demodulize
    end

    def content_type
      "Element"
    end

    def content_id
      id
    end

    def definition_hash options=nil
      options ||= {}
      hash = serializable_hash options.merge(serializable_hash_options)
      hash["type"] = object
      if hash["include_predicate"].blank?
        hash.delete "include_predicate"
      else
        hash["include_predicate_instructions"] = ::Predicator.compile hash["include_predicate"]
      end
      hash
    end

    def serializable_hash_options
      {
        methods: [:content_type],
        except: excluded_attrs
      }
    end

    def excluded_attrs
      [:created_at, :updated_at, :container_type, :container_id, :position, :url, :text]
    end

    def step
      if container.kind_of? ::RiddlerAdmin::Step
        container
      else
        container.step
      end
    end

    private

    def is_variant?
      container.kind_of? ::RiddlerAdmin::Elements::Variant
    end

    def set_defaults
      self.name = short_name.underscore if name.blank?
    end
  end
end

app/models/riddler_admin/elements/button.rb
module RiddlerAdmin
  module Elements
    class Button < Element
      validates_presence_of :text

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["text"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/copy.rb
module RiddlerAdmin
  module Elements
    class Copy < Element
      validates_presence_of :text

      def self.model_name
        Element.model_name
      end
    end
  end
end

app/models/riddler_admin/elements/external_link.rb
module RiddlerAdmin
  module Elements
    class ExternalLink < Element
      validates_presence_of :url

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["href"] = url
        hash["text"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/heading.rb
module RiddlerAdmin
  module Elements
    class Heading < Element
      validates_presence_of :text

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["text"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/image.rb
module RiddlerAdmin
  module Elements
    class Image < Element
      validates_presence_of :url

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["src"] = url
        hash["alt"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/link.rb
module RiddlerAdmin
  module Elements
    class Link < Element
      validates_presence_of :url

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["href"] = url
        hash["text"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/question.rb
module RiddlerAdmin
  module Elements
    class Question < Element
      def self.model_name
        Element.model_name
      end
    end
  end
end

app/models/riddler_admin/elements/text.rb
module RiddlerAdmin
  module Elements
    class Text < Element
      validates_presence_of :text

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["text"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/text_question.rb
module RiddlerAdmin
  module Elements
    class TextQuestion < Elements::Question
      validates_presence_of :text

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["text"] = text
        hash
      end
    end
  end
end

app/models/riddler_admin/elements/variant.rb
module RiddlerAdmin
  module Elements
    class Variant < Element
      has_many :elements, -> { order position: :asc },
        dependent: :destroy,
        as: :container

      def self.model_name
        Element.model_name
      end

      def definition_hash options=nil
        hash = super
        hash["elements"] = elements.map { |e| e.definition_hash }
        hash
      end
    end
  end
end

app/views/riddler_admin/_action.html.erb
<li class="list-group-item" id="<%= action.id %>" data-id="<%= action.id %>">
  <div>
    <%= link_to "Toggle", "#", onclick: "$('##{action.id}-detail').toggle(); return false;" %>
    <span class="handle">Move</span>
  </div>

  <h5>
    <%= action.name %>
    <span class="small text-muted"><%= action.short_name %> Action</span>
  </h5>

  <div id="<%= action.id %>-detail" class="<%= action.actionable.id %>-detail" style="display: none;">
    <div id="<%= action.id %>-form">
      <%= render partial: "riddler_admin/actions/form", locals: { action: action } %>
    </div>

    <%= render partial: action.to_partial_path("detail"), locals: { action: action } %>
  </div>
</li>

app/views/riddler_admin/_action_container.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        <h4>Enter Actions</h4>
        <a href="#" onclick="$('.<%= actionable.id %>-detail').toggle(); return false;">Toggle all</a>
      </div>
      <div class="card-body">
        <ul id="<%= actionable.id %>-enter-actions" class="list-group action-container">
          <%= render partial: "riddler_admin/action", collection: actionable.enter_actions %>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header">
        <h4>Exit Actions</h4>
        <a href="#" onclick="$('.<%= actionable.id %>-detail').toggle(); return false;">Toggle all</a>
      </div>
      <div class="card-body">
        <ul id="<%= actionable.id %>-exit-actions" class="list-group action-container">
          <%= render partial: "riddler_admin/action", collection: actionable.exit_actions %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/riddler_admin/_element.html.erb
<li class="list-group-item" id="<%= element.id %>" data-id="<%= element.id %>">
  <div>
    <%= link_to "Toggle", "#", onclick: "$('##{element.id}-detail').toggle(); return false;" %>
    <span class="handle">Move</span>
  </div>

  <h5>
    <%= element.name %>
    <span class="small text-muted"><%= element.short_name %> Element</span>
  </h5>

  <div id="<%= element.id %>-detail" class="<%= element.container.id %>-detail" style="display: none;">
    <div id="<%= element.id %>-form">
      <%= render partial: "riddler_admin/elements/form", locals: { element: element } %>
    </div>

    <%= render partial: element.to_partial_path("detail"), locals: { element: element } %>
  </div>
</li>

app/views/riddler_admin/_element_container.html.erb
<div class="card">
  <div class="card-header">
    <h4>Elements</h4>
    <a href="#" onclick="$('.<%= container.id %>-detail').toggle(); return false;">Toggle all</a>
  </div>
  <div class="card-body">
    <ul id="<%= container.id %>-elements" class="list-group element-container">
      <%= render partial: "riddler_admin/element", collection: container.elements %>
    </ul>
  </div>
</div>

app/views/riddler_admin/_email.html.erb
<li class="list-group-item" id="<%= email.id %>" data-id="<%= email.id %>">
  <div>
    <%= link_to "Toggle", "#", onclick: "$('##{email.id}-detail').toggle(); return false;" %>
    <span class="handle">Move</span>
  </div>

  <h5>
    <%= email.name %>
    <span class="small text-muted"><%= email.short_name %> Email</span>
  </h5>

  <div id="<%= email.id %>-detail" class="<%= email.emailable.id %>-detail" style="display: none;">
    <%= form_with model: email do |f| %>
      <% if email.errors.any? %>
        ERRORS
      <% end %>

      <div class="form-row">
        <div class="form-group col">
          <%= f.label :include_predicate %>
          <%= f.text_field :include_predicate, class: "form-control", placeholder: "e.g. params.user_id is present" %>
          <small class="form-text text-muted">Use data from the context that evaluates to <code>true</code> or <code>false</code></small>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col">
          <%= f.submit 'Update email', class: 'btn btn-outline-primary' %>
          <%= link_to "Delete", email, method: :delete, remote: true, data: { confirm: "Are you sure?" }, class: 'btn btn-link' %>
        </div>
      </div>

    <% end %>
  </div>
</li>

app/views/riddler_admin/_email_container.html.erb
<div class="card">
  <div class="card-header">
    <h4>Emails</h4>
    <a href="#" onclick="$('.<%= emailable.id %>-detail').toggle(); return false;">Toggle all</a>
  </div>
  <div class="card-body">
    <ul id="<%= emailable.id %>-emails" class="list-group email-container">
      <%= render partial: "riddler_admin/email", collection: emailable.emails %>
    </ul>
  </div>
</div>

app/views/riddler_admin/_main_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Riddler</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Home", "/riddler_admin", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="steps-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Steps
        </a>
        <div class="dropdown-menu" aria-labelledby="steps-dropdown">
          <%= link_to "All steps", steps_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "New step", new_step_path, class: "dropdown-item" %>
        </div>
      </li>
      <% ::RiddlerAdmin.config.content_types.each do |content_type| %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="<%= content_type %>-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= content_type.pluralize.titleize %>
          </a>
          <div class="dropdown-menu" aria-labelledby="<%= content_type %>-dropdown">
            <%= link_to "All #{content_type.pluralize}", emails_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "New #{content_type.pluralize}", new_email_path, class: "dropdown-item" %>
          </div>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="preview-contexts-dropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Preview Contexts
        </a>
        <div class="dropdown-menu" aria-labelledby="preview-contexts-dropdown">
          <%= link_to "All preview contexts", preview_contexts_path, class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "New preview context", new_preview_context_path, class: "dropdown-item" %>
        </div>
      </li>
      <% if ::RiddlerAdmin.configuration.remote_riddler? %>
        <li class="nav-item">
          <%= link_to "Publish Requests", publish_requests_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Slugs", slugs_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/riddler_admin/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top border-bottom border-white">
  <%= brand_link %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <% if ::RiddlerAdmin.config.main_app_name.present? %>
        <li class="nav-item">
          <%= link_to ::RiddlerAdmin.config.app_name, riddler_admin.root_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Contexts", preview_contexts_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Feature Flags", feature_flags_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Content", steps_path, class: "nav-link" %>
      </li>
      <% if ::RiddlerAdmin.configuration.remote_riddler? %>
        <li class="nav-item">
          <%= link_to "Publish Requests", publish_requests_path, class: "nav-link" %>
        </li>
      <% end %>
      <li class="nav-item">
        <%= link_to "Slugs", slugs_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/riddler_admin/_preview_email.html.erb
<script>
  $(document).ready(function(){
    $(".email-context-preview").first().click()
  })
</script>

<div class="row">
  <div class="col-sm-3">
    <h4>Preview Contexts</h4>
    <div class="list-group" id="preview-sections-tab" role="tablist">
      <% preview_contexts.each do |ctx| %>
        <a class="list-group-item list-group-item-action email-context-preview" id="list-preview-<%= ctx.id %>" data-email-id="<%= email.id %>" data-pctx-id="<%= ctx.id %>" data-toggle="list" href="#preview-context-<%= ctx.id %>" role="tab" aria-controls="preview-context-<%= ctx.id %>"><%= ctx.title %></a>
      <% end %>
    </div>
  </div>
  <div class="col-sm-9">
    <div class="tab-content" id="nav-tabContent">
      <% preview_contexts.each do |ctx| %>
        <div class="tab-pane fade" id="preview-context-<%= ctx.id %>" role="tabpanel" aria-labelledby="list-preview-context-<%= ctx.id %>">
          <ul class="nav nav-pills" id="<%= ctx.id %>-type" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" id="<%= ctx.id %>-visual-tab" data-toggle="tab" href="#<%= ctx.id %>-visual" role="tab" aria-controls="<%= ctx.id %>-visual" aria-selected="true">Visual</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="<%= ctx.id %>-json-tab" data-toggle="tab" href="#<%= ctx.id %>-json" role="tab" aria-controls="<%= ctx.id %>-json" aria-selected="false">JSON</a>
            </li>
          </ul>
          <div class="tab-content" id="<%= ctx.id %>-typeContent">
            <div class="tab-pane fade show active" id="<%= ctx.id %>-visual" role="tabpanel" aria-labelledby="<%= ctx.id %>-visual-tab">
            </div>
            <div class="tab-pane fade" id="<%= ctx.id %>-json" role="tabpanel" aria-labelledby="<%= ctx.id %>-json-tab">
              <pre></pre>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/riddler_admin/_step.html.erb
<li class="list-group-item" id="<%= step.id %>" data-id="<%= step.id %>">
  <div>
    <%= link_to "Toggle", "#", onclick: "$('##{step.id}-detail').toggle(); return false;" %>
    <span class="handle">Move</span>
  </div>

  <h5>
    <%= link_to step.name, step %>
    <span class="small text-muted"><%= step.short_name %> Step</span>
  </h5>

  <div id="<%= step.id %>-detail" class="<%= step.stepable.id %>-detail" style="display: none;">
    <%= form_with model: step do |f| %>
      <% if step.errors.any? %>
        ERRORS
      <% end %>

      <div class="form-row">
        <div class="form-group col">
          <%= f.label :include_predicate %>
          <%= f.text_field :include_predicate, class: "form-control", placeholder: "e.g. params.user_id is present" %>
          <small class="form-text text-muted">Use data from the context that evaluates to <code>true</code> or <code>false</code></small>
        </div>
      </div>

      <div class="form-row">
        <div class="form-group col">
          <%= f.submit 'Update step', class: 'btn btn-outline-primary' %>
          <%= link_to "Delete", step, method: :delete, remote: true, data: { confirm: "Are you sure?" }, class: 'btn btn-link' %>
        </div>
      </div>

    <% end %>
  </div>
</li>

app/views/riddler_admin/_step_container.html.erb
<div class="card">
  <div class="card-header">
    <h4>Steps</h4>
    <a href="#" onclick="$('.<%= stepable.id %>-detail').toggle(); return false;">Toggle all</a>
  </div>
  <div class="card-body">
    <ul id="<%= stepable.id %>-steps" class="list-group step-container">
      <%= render partial: "riddler_admin/step", collection: stepable.steps %>
    </ul>
  </div>
</div>